config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :encryptions, only: [:create, :new, :index, :show]
  resources :decrypts, only: [:create, :new, :index, :show]
  root"encryptions#new"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/decrypt.rb
class Decrypt < ApplicationRecord
  belongs_to :user
  validates :enc_message, format: { without: /\d/, message: "No puede contener numeros" }
  has_many :decrypt_tries
end

app/models/decrypt_try.rb
class DecryptTry < ApplicationRecord
  belongs_to :decryption, class_name: 'Decrypt', foreign_key: 'decrypt_id'

  def self.filter_attributes
    super - ['decrypt_id']
  end
end

app/models/encryption.rb
class Encryption < ApplicationRecord
  belongs_to :user
  validate :a_and_b_are_coprime
  validates :a, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :b, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 27 }
  validates :message, presence: true
  private

  def a_and_b_are_coprime
    errors.add(:base, "A must to be coprime of 27") unless coprime?(a, 27)
    errors.add(:base, "A y B must to be coprime") unless coprime?(a, b)
  end

  def coprime?(a, b)
      gcd(a, b) == 1
  end

  def gcd(a, b)
      return a if b == 0
      gcd(b, a % b)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decrypts_controller.rb
class DecryptsController < ApplicationController
  def new
    @decrypt = Decrypt.new
  end

  def create
    @decrypt = Decrypt.new(decrypt_params.merge(user_id: current_user.id))
    if @decrypt.valid?
      @decrypt.save
      DecryptService.new(decrypt: @decrypt).call!
      redirect_to decrypt_path(@decrypt), notice: 'Decryption was successfully created'
    else
      flash.now[:alert] = @decrypt.errors.full_messages.join(',')
      render :new
    end
  end

  def show
    @decrypt = Decrypt.find(params[:id])
    @decrypt_tries = @decrypt.decrypt_tries
    @frequencies = DecryptService.new(decrypt: @decrypt).character_frequency
    @frequencies_data = @frequencies.sort_by { |letter, count| count }.reverse.to_h
    @chart_data = @frequencies_data.map { |letter, count| [letter, count] }
  end

  private
  def decrypt_params
      params.require(:decrypt).permit(:enc_message)
  end
end

app/controllers/encryptions_controller.rb
class EncryptionsController < ApplicationController
    before_action :authenticate_user!
    def index
    end

    def new
        @encryption = Encryption.new
    end

    def show
        @encryption = Encryption.find(params[:id])
    end

    def create
        @encryption = Encryption.new(encryption_params.merge(user_id: current_user.id))
        if @encryption.valid?
            @encryption.save
            EncryptionService.new(encryption: @encryption).call!
            redirect_to encryption_path(@encryption), notice: 'Encryption was successfully created'
        else
            flash.now[:alert] = @encryption.errors.full_messages.join(',')
            render :new
        end
    end

    private
    def encryption_params
        params.require(:encryption).permit(:message, :a, :b)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decrypt_helper.rb
module DecryptHelper
end

app/helpers/encryption_helper.rb
module EncryptionHelper
end

app/views/decrypts/new.html.erb
<div class="container mt-5">
  <h2 class="display-5 mt-5 mb-5">Desencriptar Texto</h2>
  <%= form_with(model: @decrypt, url: decrypts_path, method: :post, class: "needs-validation", novalidate: true) do |form| %>
    <% if @decrypt.errors.any? %>
    <div class="alert alert-danger">
        <ul>
        <% @decrypt.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :enc_message, 'Ingrese el texto a desencriptar', class: "form-label" %>
      <%= form.text_area :enc_message, class: "form-control", rows: 5, required: true %>
      <div class="invalid-feedback">
        Por favor ingresa el texto que deseas desencriptar.
      </div>
    </div>
    <div class="d-grid gap-2">
      <%= form.submit "Desencriptar", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
</div>

app/views/decrypts/show.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Mensaje encriptado</h5>
          <hr>
          <p class="card-text"><%= @decrypt.enc_message %></p>
          <hr>
          <%= pie_chart @chart_data, legend: 'right', colors: ['#2ecc71', '#3498db', '#95a5a6', '#9b59b6', '#f1c40f', '#e67e22', '#e74c3c'] %>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
        <h5 class="card-title">Mensaje Descifrado</h5>
          <% if @decrypt_tries.any? %>
            <% @decrypt_tries.each do |decrypt_try| %>
              <h5>Intento con <%=decrypt_try.correspondence %></h5>
              <hr>
              <% if decrypt_try.decrypted_message.present? %>
                <p class="card-text"><%= decrypt_try.decrypted_message %></p>
                <hr>
                  <p class="card-text"><strong>Clave A:</strong> <%= decrypt_try.a %></p>
                  <p class="card-text"><strong>Clave B:</strong> <%= decrypt_try.b %></p>
                <hr>
              <% else %>
                <p class="card-text text-danger">No se pudo descifrar el mensaje.</p>
                <p class="card-text"><%= decrypt_try.error_log %></p>
              <% end %>
              <hr>
            <% end %>
          <% else %>
            <p class="card-text text-danger">No se han realizado intentos de descifrado.</p>
          <% end %>
          <%= link_to "Volver", root_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

 

app/views/encryptions/new.html.erb
<div class="container mt-5">
  <h2 class="display-5 mt-5 mb-5">Encriptar Texto</h2>
  <%= form_with(model: @encryption, url: encryptions_path, method: :post, class: "needs-validation", novalidate: true) do |form| %>
    <% if @encryption.errors.any? %>
    <div class="alert alert-danger">
        <ul>
        <% @encryption.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :message, class: "form-label" %>
      <%= form.text_area :message, class: "form-control", rows: 5, required: true %>
      <div class="invalid-feedback">
        Por favor ingresa el texto que deseas encriptar/desencriptar.
      </div>
    </div>
    <div class="row mb-3">
      <div class="col">
        <%= form.label :a, class: "form-label" %>
        <%= form.number_field :a, class: "form-control", required: true %>
        <div class="invalid-feedback">
          Por favor ingresa un valor numérico para la clave "a".
        </div>
      </div>
      <div class="col">
        <%= form.label :b, class: "form-label" %>
        <%= form.number_field :b, class: "form-control", required: true %>
        <div class="invalid-feedback">
          Por favor ingresa un valor numérico para la clave "b".
        </div>
      </div>
    </div>
    <div class="d-grid gap-2">
      <%= form.submit "Encriptar", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
</div>

app/views/encryptions/show.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Mensaje encriptado</h5>
          <hr>
          <p class="card-text"><%= @encryption.encrypted_message %></p>
          <hr>
          <p class="card-text"><strong>Clave A:</strong> <%= @encryption.a %></p>
          <p class="card-text"><strong>Clave B:</strong> <%= @encryption.b %></p>
          <hr>
          <p class="card-text"><strong>Mensaje original:</strong></p>
          <p class="card-text"><%= @encryption.message %></p>
          <hr>
          <%= link_to "Volver", root_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EncryptProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
     <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to "Mi App", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <% if user_signed_in? %>
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <%= link_to "Encriptar", new_encryption_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Desencriptar", new_decrypt_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-dark" %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %>
              </a>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>